name: Create GitHub Release

inputs:
  version:
    required: true
  changelog:
    required: true
  prerelease:
    required: false
    default: "false"
  target_branch:
    required: true
  draft:
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Create Release
      uses: softprops/action-gh-release@v2.3.2
      with:
        tag_name: ${{ inputs.version }}
        name: Release ${{ inputs.version }}
        body: ${{ inputs.changelog }}
        prerelease: ${{ inputs.prerelease }}
        target_commitish: ${{ inputs.target_branch }}
        draft: ${{ inputs.draft }}
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
