name: Get Latest Git Tag

outputs:
  latest_tag:
    description: Latest git tag
    value: ${{ steps.get.outputs.latest_tag }}

runs:
  using: composite
  steps:
    - name: Get latest tag
      id: tag
      shell: bash
      run: |
        latest_tag=$(git tag --list | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
        latest_tag=${latest_tag:-0.0.0}
        echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
