name: Get Latest Git Tag

inputs:
  tag:
    type: string
    required: false
    default: ''

outputs:
  selected_tag:
    description: Selected git tag
    value: ${{ steps.select_tag.outputs.selected_tag }}
  latest_tag:
    description: Latest git tag
    value: ${{ steps.tag.outputs.latest_tag }}

runs:
  using: composite
  steps:
    - name: ðŸ·ï¸ Get latest tag
      id: tag
      shell: bash
      run: |
        latest_tag=$(git tag --list | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
        latest_tag=${latest_tag:-0.0.0}
        echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

    - name: ðŸ·ï¸ Use provided tag or latest tag
      id: select_tag
      shell: bash
      run: |
        LATEST="${{ steps.get_tag.outputs.latest_tag }}"
        TAG_INPUT="${{ inputs.tag }}"
        
        if [[ -n "$TAG_INPUT" ]]; then
          echo "selected_tag=$TAG_INPUT" >> $GITHUB_OUTPUT
          echo "::notice ::Using provided tag: $TAG_INPUT"
        else
          echo "selected_tag=$LATEST" >> $GITHUB_OUTPUT
          echo "::notice ::Using latest tag: $LATEST"
        fi
