# ------------------------------------------------------------------------------
# Composite Action: Get Latest Git Tag
#
# This action retrieves the latest published semantic version tag from the
# repository's releases. It can also use a provided tag if specified.
#
# The action uses the GitHub CLI to query the repository's releases and
# filters for published (non-draft, non-prerelease) tags that follow
# semantic versioning format (vX.Y.Z).
#
# If no valid tag is found, it defaults to 0.0.0.
#
# Inputs:
# - tag: Optional tag to use instead of the latest tag
#
# Outputs:
# - selected_tag: The tag that was selected (either provided or latest)
# - latest_tag: The latest published semantic version tag
# ------------------------------------------------------------------------------

name: Get Latest Git Tag

inputs:
  repository:
    description: The searched repository
    default: ${{ github.repository }}
outputs:
  latest_tag:
    description: The latest published semantic version tag from the repository
    value: ${{ steps.get_tag.outputs.latest_tag }}

runs:
  using: composite
  steps:
    - name: ðŸ”§ Install gh
      uses: stetind/ppc-github-composite-actions/.github/actions/check-install-gh@__VERSION__

    - name: ðŸ”§ Install Jq
      uses: stetind/ppc-github-composite-actions/.github/actions/check-install-jq@__VERSION__

    - name: ðŸ·ï¸ Get latest tag
      id: get_tag
      shell: bash
      run: |
        # Loop through the latest releases and find the most recent published release tag
          set -eo pipefail

          page=1
          latest_tag=$(gh release list --limit 100 --json tagName,isDraft,isPrerelease \
            --jq '.[] | select(.isDraft == false and .isPrerelease == false) | .tagName' \
            | head -n 1)
  
        if [[ -n "$latest_tag" ]]; then
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
          echo "::notice ::Latest published semver tag found: $latest_tag"
        else
          echo "::warning ::No valid semver published release tag found, using 0.0.0"
          echo "latest_tag=0.0.0" >> $GITHUB_OUTPUT
        fi
