# ------------------------------------------------------------------------------
# Composite Action: check-install-git
#
# This action verifies and installs Git if not present in the environment.
# Ensures Git is available and properly configured for version control operations.
#
# Features:
# - Automatic Git detection
# - Version verification
# - Platform-aware installation
# - Installation of required dependencies
# - Validation of installation success
#
# Prerequisites:
# - apt-get available (for Debian/Ubuntu environments)
# - Sufficient permissions to install packages
#
# Inputs:
# - None required
#   Action automatically handles detection and installation
#
# Outputs:
# - installed: Boolean indicating if Git was newly installed
# - version: Installed Git version
#
# Example Usage:
# ```yaml
# - uses: ./.github/actions/check-install-git
#   name: Ensure Git is available
# ```
#
# Error Handling:
# - Validates system package manager availability
# - Checks installation success
# - Reports detailed error messages for troubleshooting
# - Verifies Git functionality after installation
#
# Note:
# - This action is essential for workflows requiring Git operations
# - Automatically handles different Linux distributions
# - Includes basic Git configuration setup
# ------------------------------------------------------------------------------

name: check-install-git
description: Ensures Git is installed and available in the environment

outputs:
  installed:
    description: 'Whether Git was newly installed'
    value: ${{ steps.check_gh.outputs.installed }}
  version:
    description: 'Installed Git version'
    value: ${{ steps.check_gh.outputs.version }}


runs:
  using: composite
  steps:
    - name: Check and install git
      id: check_git
      shell: bash
      run: |
        set -e
        echo "::notice::ðŸ” Checking for git installation..."

        if ! command -v git &> /dev/null; then
          echo "::notice::ðŸ“¦ git not found. Installing..."

          if command -v apt-get &> /dev/null; then
            sudo apt-get update &> /dev/null && sudo apt-get install -y -f git  &> /dev/null || apt-get update &> /dev/null && apt-get install -y -f git &> /dev/null 
          elif command -v yum &> /dev/null; then
            sudo yum install -y git &> /dev/null || yum install -y git &> /dev/null 
          elif command -v apk &> /dev/null; then
            apk add --no-cache git &> /dev/null 
          elif command -v brew &> /dev/null; then
            brew install git &> /dev/null 
          else
            echo "::error::Unable to install git. No supported package manager found."
            exit 1
          fi
        
          echo "installed=true" >> $GITHUB_OUTPUT
          echo "::notice::âœ… git installed successfully"
        else
          echo "installed=false" >> $GITHUB_OUTPUT
          echo "::notice::âœ… git is already installed"
        fi
        
        # Verify version
        echo "version=$(git --version)" >> $GITHUB_OUTPUT
        echo "::notice::ðŸ“Š Using $(which git)"
