# ------------------------------------------------------------------------------
# Composite Action: check-install-jq
#
# This action verifies and installs jq (lightweight command-line JSON processor)
# if not present in the environment. Essential for JSON parsing in workflows.
#
# Features:
# - Automatic jq detection
# - Version verification
# - Platform-aware installation
# - Minimal dependency footprint
# - Installation validation
#
# Prerequisites:
# - apt-get available (for Debian/Ubuntu environments)
# - Sufficient permissions to install packages
#
# Inputs:
# - None required
#   Action automatically handles detection and installation
#
# Outputs:
# - installed: Boolean indicating if jq was newly installed
# - version: Installed jq version
#
# Example Usage:
# ```yaml
# - uses: ./.github/actions/check-install-jq
#   name: Ensure jq is available
# ```
#
# Example jq Usage After Installation:
# ```yaml
# - run: |
#     echo '{"name": "test"}' | jq -r '.name'
# ```
#
# Error Handling:
# - Validates package manager availability
# - Verifies installation success
# - Reports clear error messages
# - Checks jq functionality post-installation
#
# Note:
# - Critical for workflows processing JSON data
# - Lightweight installation (~200KB)
# - Compatible with all major Linux distributions
# ------------------------------------------------------------------------------


name: check-install-jq
description: Ensures jq JSON processor is installed and available

outputs:
  installed:
    description: 'Whether jq was newly installed'
    value: ${{ steps.check_gh.outputs.installed }}
  version:
    description: 'Installed jq version'
    value: ${{ steps.check_jq.outputs.version }}
runs:
  using: composite
  steps:
    - name: Check and install jq
      id: check_jq
      shell: bash
      run: |
        set -e
        echo "::notice::🔍 Checking for jq installation..."

        if ! command -v jq &> /dev/null; then
          echo "::notice::📦 jq not found. Installing..."

          if command -v apt-get &> /dev/null; then
            sudo apt-get update &> /dev/null && sudo apt-get install -y -f jq &> /dev/null || apt-get update &> /dev/null && apt-get install -y -f jq &> /dev/null 
          elif command -v yum &> /dev/null; then
            sudo yum install -y jq &> /dev/null || yum install -y jq &> /dev/null 
          elif command -v apk &> /dev/null; then
            apk add --no-cache jq &> /dev/null 
          elif command -v brew &> /dev/null; then
            brew install jq &> /dev/null 
          else
            echo "::error::Unable to install jq. No supported package manager found."
            exit 1
          fi
        
          echo "installed=true" >> $GITHUB_OUTPUT
          echo "::notice::✅ jq installed successfully"
        else
          echo "installed=false" >> $GITHUB_OUTPUT
          echo "::notice::✅ jq is already installed"
        fi
        
        # Verify version
        echo "version=$(jq --version)" >> $GITHUB_OUTPUT
        echo "::notice::📊 Using $(jq --version)"
