# ------------------------------------------------------------------------------
# Composite Action: delete-branch
#
# Safely deletes Git branches with validation and error handling.
# Can handle both local and remote branches.
#
# Features:
# - Safe branch deletion
# - Remote branch support
# - Protected branch checks
# - Default branch protection
# - Validation checks
#
# Prerequisites:
# - GitHub token with branch deletion permissions
# - gh CLI (automatically installed)
#
# Inputs:
# - token:
#   Required: true
#   Description: GitHub token with branch deletion permissions
#
# - branch:
#   Required: true
#   Description: Name of the branch to delete
#
# - force:
#   Required: false
#   Default: 'false'
#   Description: Force delete the branch even if not merged
#
# Outputs:
# - success:
#   Description: Boolean indicating if the branch was deleted successfully
# -------


name: Delete Branch
description: Safely deletes a specified branch from a GitHub repository

inputs:
  token:
    description: 'GitHub token with branch deletion permissions'
    required: true
  branch:
    description: 'Name of the branch to delete'
    required: true
  force:
    description: 'Force delete the branch even if not merged'
    required: false
    default: 'false'


runs:
  using: "composite"
  steps:
    - name: 🗑️ Delete Branch
      id: delete_branch
      uses: dawidd6/action-delete-branch@v3
      with:
        github_token: ${{ inputs.token }}
        branches: ${{ inputs.branch }}