name: Create PR
description: Creates and optionally merges a pull request with support for branch cleanup

inputs:
  token:
    description: 'GitHub token with permissions for PR creation and merging'
    required: true
  title:
    description: 'Title for the pull request (defaults to "New Release")'
    required: false
    default: 'New Release'
  body:
    description: 'Body for the pull request (defaults to "New Release")'
    required: false
    default: '-'
  target:
    description: 'Target branch for the pull request'
    required: false
    default: 'main'
  source:
    description: 'Source branch for the pull request'
    required: true
outputs:
  pr_url:
    description: 'The URL of the created / merged PR'
    value: ${{ steps.create_pr.outputs.pr_url }}

runs:
  using: "composite"
  steps:
    - name: 🔧 Install gh CLI
      uses: stetind/ppc-github-composite-actions/.github/actions/check-install-gh@v2.0.1

    - name: 🔧 Setup Git
      uses: stetind/ppc-github-composite-actions/.github/actions/git-setup@v2.0.1

    - name: 🔄 Create Pull Request
      id: create_pr
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        # First check if PR already exists
        EXISTING_PR=$(gh pr list --head "${{ inputs.source }}" --base "${{ inputs.target }}" --json url --jq '.[0].url')
        
        if [ -n "$EXISTING_PR" ]; then
          echo "::notice::Using existing pull request: $EXISTING_PR"
          echo "pr_url=$EXISTING_PR" >> $GITHUB_OUTPUT
        else
          # Create new PR if none exists
          PR_URL=$(gh pr create \
            --base "${{ inputs.target }}" \
            --head "${{ inputs.source }}" \
            --title "${{ inputs.title }}" \
            --body "${{ inputs.body }}")
        
          if [ $? -eq 0 ]; then
            echo "::notice::Pull request created successfully: $PR_URL"
            echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
          else
            echo "::error::Failed to create pull request"
            echo "pr_url=''" >> $GITHUB_OUTPUT
          fi
        fi
