# ------------------------------------------------------------------------------
# Composite Action: Generate Changelog
#
# This action generates a Markdown changelog based on conventional commits
# between a previous Git tag and the current HEAD. It supports automatic
# version bumping and allows overriding the tag manually. Designed for use in
# automated release workflows.
#
# Features:
# - Extracts commit messages since the last tag
# - Determines whether a changelog should be created (or forced)
# - Computes a new semantic version based on commit types (if new_tag not provided)
# - Outputs a changelog in Markdown format
#
# Inputs:
# - previous_tag: The tag to compare commits against (required)
# - new_tag: Optional tag to use for changelog; if omitted, computed automatically
# - repository: GitHub repo in owner/repo format
# - force: Forces changelog generation even if no commits detected
#
# Outputs:
# - new_tag: The version to be used in the release
# - has_changes: Whether changelog was generated (based on commits or force)
# - changelog: Markdown string of the generated changelog
#
# Requires:
# - stetind/ppc-github-composite-actions/.github/actions/get-commits-since-tag@__VERSION__
# - stetind/ppc-github-composite-actions/.github/actions/check-should-proceed@__VERSION__
# - stetind/ppc-github-composite-actions/.github/actions/detect-version-bump@__VERSION__
# - stetind/ppc-github-composite-actions/.github/actions/generate-changelog@__VERSION__
# ------------------------------------------------------------------------------

name: Generate Changelog

inputs:
  previous_tag:
    required: true
  new_tag:
    required: false
    default: ''
  repository:
    required: true
  force:
    required: false
    default: 'false'

outputs:
  new_tag:
    value: ${{ steps.version.outputs.new_tag }}
  has_changes:
    value: ${{ steps.check_commits.outputs.proceed == 'true' }}
  changelog:
    description: Markdown changelog
    value: ${{ steps.log.outputs.changelog }}

runs:
  using: composite
  steps:
    - name: ðŸ“¦ Get commits since selected tag
      id: get_commits
      uses: stetind/ppc-github-composite-actions/.github/actions/get-commits-since-tag@__VERSION__
      with:
        tag: ${{ inputs.previous_tag }}

    - name: ðŸš¨ Check if commits found or force proceed
      id: check_commits
      uses: stetind/ppc-github-composite-actions/.github/actions/check-should-proceed@__VERSION__
      with:
        commits: ${{ steps.get_commits.outputs.commits }}
        force: ${{ inputs.force }} 
          
    - name: ðŸ” Detect version bump and compute new version
      id: detect_version
      if: inputs.new_tag == ''
      uses: stetind/ppc-github-composite-actions/.github/actions/detect-version-bump@__VERSION__
      with:
        commits: ${{ steps.get_commits.outputs.commits }}
        tag: ${{ inputs.previous_tag }}

    - name: Set Target tag
      id: version
      shell: bash
      run: |
          if [[ -n "${{ inputs.new_tag }}" ]]; then
            echo "new_tag=${{ inputs.new_tag }}" >> $GITHUB_OUTPUT
          else
            echo "new_tag=${{ steps.detect_version.outputs.new_version }}" >> $GITHUB_OUTPUT
          fi
          
    - name: Generate grouped ChangeLog
      id: log
      if: steps.check_commits.outputs.proceed == 'true'
      uses: stetind/ppc-github-composite-actions/.github/actions/generate-changelog@__VERSION__
      with:
        commits: ${{ steps.get_commits.outputs.commits }}
        previous_tag: ${{ inputs.previous_tag }}
        new_tag: ${{ steps.version.outputs.new_tag }}
        repository: ${{ inputs.repository }}
