name: Generate Changelog

inputs:
  previous_tag:
    required: true
  new_tag:
    required: true
  repository:
    required: true
  force:
    required: false
    default: 'false'

outputs:
  has_changes:
    value: ${{ steps.log.outputs.has_changes }}
  changelog:
    description: Markdown changelog
    value: ${{ steps.log.outputs.changelog }}

runs:
  using: composite
  steps:
    - name: 📦 Get commits since selected tag
      id: get_commits
      uses: stetind/ppc-github-composite-actions/.github/actions/get-commits-since-tag@main
      with:
        tag: ${{ inputs.previous_tag }}

    - name: 🚨 Check if commits found or force proceed
      id: check_commits
      uses: stetind/ppc-github-composite-actions/.github/actions/check-should-proceed@main
      with:
        commits: ${{ steps.get_commits.outputs.commits }}
        force: ${{ inputs.force }} 
    
    - name: Generate grouped ChangeLog
      id: log
      if: steps.check_commits.outputs.proceed == 'true'
      uses: stetind/ppc-github-composite-actions/.github/actions/generate-changelog@main
      with:
        commits: ${{ steps.get_commits.outputs.commits }}
        previous_tag: ${{ inputs.previous_tag }}
        new_tag: ${{ inputs.new_tag }}
        repository: ${{ inputs.repository }}
