# ------------------------------------------------------------------------------
# Composite Action: check-install-gh
#
# This action ensures the GitHub CLI (`gh`) is available on the runner.
# If not found, it installs the GitHub CLI using apt package manager.
#
# Supported package managers:
# - apt (Ubuntu/Debian)
#
# This action is useful as a prerequisite for any step or action that interacts
# with GitHub repositories, issues, pull requests, or releases through the
# command line.
#
# Behavior:
# - Installs GitHub CLI (gh) using apt
#
# Output:
# - GitHub CLI will be available for subsequent steps
# ------------------------------------------------------------------------------

name: check-install-gh
description: 'Ensures GitHub CLI (gh) is installed and available on the runner. Installs it if missing.'

runs:
  using: composite
  steps:
    - name: Check and install gh
      id: check_gh
      shell: bash
      run: |
        set -e
        echo "::notice::🔍 Checking for gh installation..."

        if ! command -v gh &> /dev/null; then
          echo "::notice::📦 gh not found. Installing..."

          if command -v apt-get &> /dev/null; then
            sudo apt-get update &> /dev/null && sudo apt-get install -y -f gh  &> /dev/null || apt-get update &> /dev/null && apt-get install -y -f gh &> /dev/null 
          elif command -v yum &> /dev/null; then
            sudo yum install -y gh &> /dev/null || yum install -y gh &> /dev/null 
          elif command -v apk &> /dev/null; then
            apk add --no-cache gh &> /dev/null 
          elif command -v brew &> /dev/null; then
            brew install gh &> /dev/null 
          else
            echo "::error::Unable to install gh. No supported package manager found."
            exit 1
          fi

          echo "::notice::✅ gh installed successfully"
        else
          echo "::notice::✅ gh is already installed"
        fi

        # Verify gh version
        JQ_VERSION=$(gh --version)
        echo "::notice::📊 Using $gh_VERSION"