# ------------------------------------------------------------------------------
# Composite Action: Final Summary
#
# This action generates a final summary of the release process, displaying
# important information about the release such as the tag, release type
# (production or pre-release), and the URL to the GitHub release.
#
# Inputs:
# - version: The version tag of the release (e.g., v1.2.3)
# - prerelease: The pre-release identifier, if applicable (empty for production releases)
# ------------------------------------------------------------------------------

name: Final Summary
description: Generates a final summary of the release process

inputs:
  version:
    required: true
    description: 'The version tag of the release (e.g., v1.2.3)'
  prerelease:
    required: false
    default: ""
    description: 'The pre-release identifier, if applicable (empty for production releases)'

runs:
  using: composite
  steps:
    - name: Print summary
      shell: bash
      run: |
        repo="${{ github.repository }}"
        url="https://github.com/${repo}/releases/tag/${{ inputs.version }}"

        echo "::notice ::\ud83d\udcc6 Release Summary"
        echo "::notice ::\ud83d\udd16 Tag: ${{ inputs.version }}"

        if [[ "${{ inputs.prerelease }}" != "" && "${{ inputs.prerelease }}" != "none" ]]; then
          echo "::notice ::\ud83d\udea7 Pre-release: ${{ inputs.prerelease }}"
        else
          echo "::notice ::\u2705 Production Release"
        fi

        echo "::notice ::\ud83d\udd17 URL: $url"
        echo "::notice ::\ud83c\udf89 Release successfully created!"
