# ------------------------------------------------------------------------------
# Composite Action: Get Commits Since Tag
#
# This action extracts all commit messages since a specified Git tag.
# It handles sanitization of commit messages to ensure they can be safely
# processed in GitHub Actions workflows.
#
# The action supports comparing from a specific tag or from the beginning
# of the repository history (when tag is "0.0.0").
#
# Inputs:
# - tag: Git tag to use as the starting point for commit extraction
#
# Outputs:
# - commits: String containing all commit messages (subject§body format with escaped pipe and section sign characters)
# ------------------------------------------------------------------------------

name: Get Commits Since Tag

description: Extract commits since given tag

inputs:
  tag:
    required: true
    description: Git tag to use as the starting point for commit extraction (use "0.0.0" to include all commits)

outputs:
  commits:
    description: A multiline string of all commit messages since the specified tag.
    value: ${{ steps.commits.outputs.commits }}

runs:
  using: composite
  steps:
    - name: Set safe Directory
      id: safe_dir
      shell: bash
      run: |
        git config --global --add safe.directory "$(pwd)"
    
    - name: Get commits
      id: commits
      shell: bash
      run: |
        # Function to escape backtick-wrapped content
        escape_backticks() {
          echo "$1" | sed 's/`\([^`]*\)`/\\`\1\\`/g'
        }
        
        if [[ "${{ inputs.tag }}" != "0.0.0" ]]; then
          raw_commits=$(git log "${{ inputs.tag }}"..HEAD --pretty=format:"%s|%b")
        else
          raw_commits=$(git log HEAD --pretty=format:"%s|%b")
        fi
        
        # Escape the commits
        escaped_commits=$(escape_backticks "$raw_commits")
        
        echo "commits<<EOF" >> $GITHUB_OUTPUT
        echo "$escaped_commits" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

