name: Checkout Repository

inputs:
  branch:
    required: true
    description: Branch or ref to checkout

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
        fetch-depth: 0
