# ------------------------------------------------------------------------------
# Composite Action: check-should-proceed
#
# This action determines whether a release process should proceed based on:
# 1. The presence of commits (provided as text input)
# 2. A force flag that can override the commit check
#
# The action is typically used in release workflows to prevent empty releases
# when no new commits are available since the last release.
#
# Behavior:
# - Returns proceed=false if no commits are found and force is not true
# - Returns proceed=true if commits are found or force is true
# - Logs a warning when skipping due to no commits
#
# Output:
# - proceed: Boolean indicating whether to proceed with release
# ------------------------------------------------------------------------------

name: Check if Should Proceed

inputs:
  commits:
    required: true
    description: 'String containing commit data to evaluate (subject§body format with escaped pipe and section sign characters)'
  force:
    required: true
    description: 'Boolean flag to force proceeding even when no commits are found'

outputs:
  proceed:
    description: Whether to proceed with release
    value: ${{ steps.check.outputs.proceed }}

runs:
  using: composite
  steps:
    - name: Determine whether to proceed
      id: check
      shell: bash
      run: |
        if [[ -z "${{ inputs.commits }}" ]]; then
          if [[ "${{ inputs.force }}" != "true" ]]; then
            echo "proceed=false" >> $GITHUB_OUTPUT
            echo "::warning ::No commits found. Skipping release."
            exit 0
          fi
        fi
        echo "proceed=true" >> $GITHUB_OUTPUT
