# ------------------------------------------------------------------------------
# Composite Action: create-dot-env
#
# Creates or updates a .env file by combining environment variables from multiple sources.
#
# Features:
# - Direct environment variable processing
# - Pattern-based variable filtering
# - GitHub Secrets integration
# - Custom variable support
# - Secure file handling
# - Directory path support
#
# Prerequisites:
# - Write permissions in target directory
# - jq for JSON processing (automatically installed)
#
# Inputs:
# - variable_pattern:
#   Required: false
#   Default: '.*'
#   Description: Regex pattern to filter environment variables
#
# - secrets:
#   Required: false
#   Description: JSON string of GitHub secrets to include
#
# - variables:
#   Required: false
#   Description: JSON object of additional variables to include
#
# - volume:
#   Required: false
#   Default: '.env'
#   Description: Target  for the .env file
#
# Example Usage:
# ```yaml
# - uses: ./.github/actions/create-dot-env
#   with:
#     variable_pattern: '^APP_.*'
#     secrets: ${{ toJSON(secrets) }}
#     variables: '{"CUSTOM_VAR": "value"}'
#     volume: './config/.env'
# ```
#
# Error Handling:
# - Validates input parameters
# - Ensures directory existence
# - Handles special characters
# - Reports clear error messages
# ---------------------------------------

name: create-dot-env
description: Creates a .env file from environment variables and secrets

inputs:
  variable_pattern:
    required: false
    description: 'Regex pattern to filter environment variables'
    default: ^[A-Za-z].*
  secrets:
    required: false
    description: 'JSON string of secrets to include'
    default: "{}"
  variables:
    required: false
    description: 'JSON string of additional variables'
    default: "{}"
  volume:
    required: false
    description: 'Target path for the .env file'
    default: "/workspace"

runs:
  using: composite
  steps:
    - name: 🔧 Install Jq
      uses: stetind/ppc-github-composite-actions/.github/actions/check-install-jq@v1.0.5

    - name: 🔧 Secret to Environment
      uses: oNaiPs/secrets-to-env-action@v1.5
      with:
        secrets: ${{ inputs.secrets }}

    - name: 📓 Fill [dot] Env (Generic)
      uses: CallePuzzle/envvar-to-dotenv-action@v1.2.4
      with:
        variableNamesByFilter: ${{ inputs.variable_pattern }}

    - name: 🔧 Vars to Environment
      shell: bash
      run: |
        declare -A obj
        echo '${{ inputs.variables }}' > ${{ inputs.volume }}/.vars_json

        while read -r key value; do
          obj[$key]=$value
        done <<< $(jq -r 'to_entries[] | "\(.key) \(.value)"' ${{ inputs.volume }}/.vars_json)

        echo '' >> ${{ inputs.volume }}/.env

        for key in "${!obj[@]}"; do
          value=${obj[$key]}
          echo "$key=${obj[$key]}" >> ${{ inputs.volume }}/.env
        done