# =============================================================================
# 📦 Execute Release Process
#
# Description:
#   Workflow that triggers the release execution process when release
#   preparation is complete and changes are pushed to the release branch.
#
# Features:
#   • Automatic trigger on release branch updates
#   • Configurable execution environment
#   • Release completion handling
#
# Trigger: push (branch: releases)
# Dependencies: reusable-release-execution.yaml
# =============================================================================

name: 📦 Run Release

on:
  push:
    branches:
      - releases

jobs:
  execution:
    name: Run Release
    uses: stetind/ppc-reusable-workflows/.github/workflows/release-execution.yaml@v10.0.2
    secrets: inherit
    with:
      target: ${{ github.event.repository.default_branch }}
      temporary: 'releases'
      runner: ${{ vars.DEFAULT_RUNNER }}

